Morningpaper
Coding-Algorithm-for-the-Last-time/Today-I-solved pull request #11
Opened 2023-03-11 12:28 UTC by morningpaper

다시 수정해서 올렸습니다 ㅎㅎ
잘부탁드립니다.

2023-03-11 12:45 UTC, hoetaek requested changes
오 하루만에 배워서 올리시다니 수고하셨어요!
우리 파일 이름을 그냥 닉네임만으로 하기로 해서 수정 부탁해요ㅠㅠ
그리고 두개 파일 삭제하셔서 올리셨는데 반영되면 설탕쌤 풀이랑 문제 파일이 삭제됩니다ㅠ 이것만 수정해주세요~
거의 다 했습니다!

2023-03-12 13:41 UTC, morningpaper commented
아 그렇군요;;
알겠습니다! 오늘은 하루종인 밖에 있어서 수정을 못했네요!! 얼른하겠습니다!

2023년 3월 11일 (토) 오후 9:46, hoetaek ***@***.***>님이 작성:

> ***@***.**** requested changes on this pull request.
>
> 오 하루만에 배워서 올리시다니 수고하셨어요!
> 우리 파일 이름을 그냥 닉네임만으로 하기로 해서 수정 부탁해요ㅠㅠ
> 그리고 두개 파일 삭제하셔서 올리셨는데 반영되면 설탕쌤 풀이랑 문제 파일이 삭제됩니다ㅠ 이것만 수정해주세요~
> 거의 다 했습니다!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Coding-Algorithm-for-the-Last-time/Today-I-solved/pull/11#pullrequestreview-1335861346>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2QHRM2MMFZLPGTCHFTDIRLW3RXY7ANCNFSM6AAAAAAVXOULTY>
> .
> You are receiving this because you authored the thread.Message ID:
> <Coding-Algorithm-for-the-Last-time/Today-I-solved/pull/11/review/1335861346
> @github.com>
>

2023-03-13 05:30 UTC, hoetaek approved these changes
처음 git 하시는데 훌륭하십니다!

2023-03-13 05:31 UTC, merged

2023-03-13 06:00 UTC, morningpaper commented
감사합니다 선생님!
좀더 익숙해져보도록 하겠습니다!^^

2023년 3월 13일 (월) 오후 2:31, hoetaek ***@***.***>님이 작성:

> ***@***.**** approved this pull request.
>
> 처음 git 하시는데 훌륭하십니다!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Coding-Algorithm-for-the-Last-time/Today-I-solved/pull/11#pullrequestreview-1336267358>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2QHRMZKPD3IP3MIARGHG53W32WJ5ANCNFSM6AAAAAAVXOULTY>
> .
> You are receiving this because you authored the thread.Message ID:
> <Coding-Algorithm-for-the-Last-time/Today-I-solved/pull/11/review/1336267358
> @github.com>
>